
from django.contrib import admin
from django.urls import path

from MyApp import views

urlpatterns = [
    path('add_notification_get/',views.add_notification_get),
    path('add_startupidea_get/',views.add_startupidea_get),
    path('expertregister/',views.expertregister),
    path('expertregister_post/',views.expertregister_post),
    path('login_post/',views.login_post),
    path('admin_home_get/',views.admin_home_get),
    path('change_password_get/',views.change_password_get),
    path('edit_startup_idea_get/<id>',views.edit_startup_idea_get),
    path('edit_startup_idea_post/',views.edit_startup_idea_post),
    path('expert_get/',views.expert_get),
    path('add_notification_post/',views.add_notification_post),
    path('company_get/',views.company_get),
    path('login_get/',views.login_get),
    path('view_suggestion_expert/',views.view_suggestion_expert),
    path('delete_startup/<id>',views.delete_startup),
    path('sendreplys/<id>',views.sendreplys),
    path('sendreplyspost/',views.sendreplyspost),
    path('view_complaint_get/',views.view_complaint_get),
    path('view_notification_get/',views.view_notification_get),
    path('view_startup_all/',views.view_startup_all),
    path('view_startup_gets/',views.view_startup_gets),
    path('view_system_feedback_get/',views.view_system_feedback_get),
    path('add_startupidea_post/',views.add_startupidea_post),
    path('delete_notification/<id>',views.delete_notification),
    path('change_passwordpost/',views.change_passwordpost),
    path('Updateprofile_post/',views.Updateprofile_post),

####################EXPERT#################################################

    path('expert_change_password_get/',views.expert_change_password_get),

    path('Add_legal_details_get/',views.details_get),
    path('doubt_reply_get/',views.doubt_reply_get),
    path('manage_legal_guide_get/',views.manage_legal_guide_get),
    path('add_legal_guide/',views.add_legal_guide),
    path('add_legal_guide_Post/',views.add_legal_guide_Post),
    path('delete_legal_guide/<id>',views.delete_legal_guide),
    path('suggestion_add_get/',views.suggestion_add_get),
    path('update_profile_get/',views.update_profile_get),
    path('view_doubt_get/',views.view_doubt_get),
    path('expert_view_notification_get/',views.expert_view_notification_get),
    path('expert_view_Request_get/',views.expert_view_Request_get),
    path('logout_get/',views.logout_get),
    path('user_details__get/',views.user_detail_get),
    path('view_profile_get/',views.view_profile_get),
    path('view_suggestion_get/',views.view_suggestion_get),
    path('add_suggestion/',views.add_suggestion),
    path('add_suggestion_post/',views.add_suggestion_post),
    path('delete_suggestion/<id>',views.delete_suggestion),
    path('view_feedback_get/',views.view_feedback_get),
    path('change_password_get_expert/',views.change_password_get_expert),
    path('change_passwordpost_expert/',views.change_passwordpost_expert),
    path('expert_home_get/',views.expert_home_get),
    path('acceptexpert/<id>',views.acceptexpert),
    path('rejectexpert/<id>',views.rejectexpert),
    path('blockexpert/<id>',views.blockexpert),
    path('unblockexpert/<id>',views.unblockexpert),
    path('acceptcompany/<id>',views.acceptcompany),
    path('rejectcompany/<id>',views.rejectcompany),
    path('blockcompany/<id>',views.blockcompany),
    path('unblockcompany/<id>',views.unblockcompany),
    path('acceptrequest/<id>',views.acceptrequest),
    path('rejectrequest/<id>',views.rejectrequest),
    path('deleteskill/',views.deleteskill),
    path('view_complaints/',views.view_complaints),

    path('loginpost/',views.loginpost),
    path('company_register/',views.company_register),
    path('updateprofile/',views.updateprofile),
    path('viewprofile/',views.viewprofile),
    path('change_passwordpost_company/',views.change_passwordpost_company),
    path('view_notification/',views.view_notification),
    path('view_startup/',views.view_startup),
    path('sendfeedback_post/',views.sendfeedback_post),

    path('user_register/',views.user_register),
    path('change_passwordpost_user/',views.change_passwordpost_user),
    path('add_skill/',views.add_skill),
    path('view_skill_user/',views.view_skill_user),
    path('sendfeedback_user/',views.sendfeedback_user),
    path('send_expert_feedback/',views.send_expert_feedback),
    path('sendrequest/',views.sendrequest),
    path('view_expert/',views.view_expert),
    path('view_company/',views.view_company),
    path('view_notification_user/',views.view_notification_user),
    path('view_skills/',views.view_skills),
    path('view_startup_user/',views.view_startup_user),
    path('add_startup_user/',views.add_startup_user),
    path('Edit_startup_Post/',views.Edit_startup_Post),
    path('delete_startup_Post/',views.delete_startup_Post),
    # path('view_trending_startup_user/',views.view_trending_startup_user),
    path('viewprofile_user/',views.viewprofile_user),
    path('updateprofile_user/',views.updateprofile_user),
    path('send_complaint_user/',views.send_complaint_user),
    path('complaintViewflutter/',views.complaintViewflutter),
    path('send_doubt_user/',views.send_doubt_user),
    path('doubt_View_user/',views.doubt_View_user),
    path('sendreply_doubt/<id>',views.sendreply_doubt),
    path('sendreplyspost_doubt/',views.sendreplyspost_doubt),
    path('User_sendchat/',views.User_sendchat),
    path('User_viewchat/',views.User_viewchat),
    path('sendrequest_company/',views.sendrequest_company),
    path('view_request_status/',views.view_request_status),
    path('user_view_request_status/',views.user_view_request_status),

    path('send_fund/',views.send_fund),
    path('view_fundoffer_user/',views.view_fundoffer_user),
    path('approve_request/',views.approve_request),
    path('reject_request/',views.reject_request),
    path('NLP_Startup_Recommendation/',views.NLP_Startup_Recommendation),
    path('NLP_trending_user_Startup/',views.NLP_trending_user_Startup),
    path('gemini/',views.gemini_chat),
    path('send_request_toexpert/',views.send_request_toexpert),
    path('analyze_startup_idea/', views.ajax_analyze_startup, name='analyze_startup_idea'),


]
