# Generated by Django 5.1.5 on 2026-01-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_table',
            name='name',
        ),
    ]
