# Generated by Django 5.1.5 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_company_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_table',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
