# Generated by Django 5.2.6 on 2026-02-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_company_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_table_expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.expert_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.users_table')),
            ],
        ),
    ]
