# Generated by Django 5.2.6 on 2026-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_request_table_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table_expert',
            name='request',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
